"""CrossHair result-parsing and helper functions.

Extracted from crosshair_adapter.py to keep module sizes manageable.
Contains functions for classifying exceptions, unwrapping checkables,
converting CrossHair messages to findings, and parsing CLI output.

This is a core checker module — it contains pure result-parsing logic
with no I/O and is subject to full structural verification.
"""

from __future__ import annotations

import os
import re
import sys
from typing import Any

import icontract

from serenecode.contracts.predicates import is_non_empty_string, is_positive_int
from serenecode.ports.symbolic_checker import SymbolicFinding


# Exception types and message patterns that indicate solver limitations,
# not actual bugs in the code under verification.
_SOLVER_LIMITATION_TYPES = (RecursionError,)
_SOLVER_LIMITATION_PATTERNS = (
    "unhashable type",
    "symbolicbool",
    "notdeterministic",
    "not deterministic",
    "non-string object",
    "returned a non-",
    "must be a string, bytes or ast",
    "must be a string or",
)


@icontract.require(lambda exc: isinstance(exc, Exception), "exc must be an Exception")
@icontract.ensure(
    lambda result: result in {"unsupported", "error"},
    "result must be a recognized symbolic outcome",
)
def _classify_exception(exc: Exception) -> str:
    """Classify an exception as a solver limitation or a real error.

    Args:
        exc: The exception raised during verification.

    Returns:
        "unsupported" for solver limitations, "error" for real errors.
    """
    if isinstance(exc, _SOLVER_LIMITATION_TYPES):
        return "unsupported"
    error_str = str(exc).lower()
    # Loop invariant: checked patterns[0..i]
    for pattern in _SOLVER_LIMITATION_PATTERNS:
        if pattern in error_str:
            return "unsupported"
    if "unsupported" in error_str or "not implemented" in error_str:
        return "unsupported"
    return "error"


_AUTOGEN_DUNDER_NAMES = frozenset({
    "__hash__", "__eq__", "__ne__", "__repr__", "__str__",
})

_CHECKABLE_WRAPPER_ATTRS = ("_checkable", "inner", "_inner")


@icontract.require(lambda checkable: checkable is not None, "checkable must be provided")
@icontract.ensure(lambda result: isinstance(result, bool), "result must be a bool")
def _is_autogenerated_dunder(checkable: Any) -> bool:
    """Check if a checkable is an auto-generated dataclass dunder method.

    Python's dataclass machinery generates __eq__, __hash__, __repr__,
    etc. These are guaranteed correct and don't need symbolic verification.

    Args:
        checkable: A CrossHair Checkable.

    Returns:
        True if this is an auto-generated dataclass dunder method.
    """
    name = _extract_func_name_from_checkable(checkable)
    if name not in _AUTOGEN_DUNDER_NAMES:
        return False

    # Try to find the owning class via the function's __qualname__
    inner = _unwrap_checkable(checkable)
    ctxfn = getattr(inner, "ctxfn", None)
    if ctxfn is None:
        return False
    fn = getattr(ctxfn, "fn", None)
    if fn is None:
        return False
    qualname = getattr(fn, "__qualname__", "")
    if "." not in qualname:
        return False
    # e.g. "SourceFile.__hash__" — get the class
    cls_name = qualname.rsplit(".", 1)[0]
    module = getattr(fn, "__module__", None)
    if not module:
        return False
    import sys
    mod = sys.modules.get(module)
    if mod is None:
        return False
    cls = getattr(mod, cls_name, None)
    if cls is None:
        return False
    return hasattr(cls, "__dataclass_fields__")


@icontract.require(lambda checkable: checkable is not None, "checkable must be provided")
@icontract.ensure(lambda result: isinstance(result, str), "result must be a string")
def _extract_func_name_from_checkable(checkable: Any) -> str:
    """Extract function name from a CrossHair Checkable object.

    Handles wrapper types like ClampedCheckable by unwrapping
    to find the inner ConditionCheckable with the actual name.

    Args:
        checkable: A CrossHair Checkable.

    Returns:
        The function name string.
    """
    inner = _unwrap_checkable(checkable)

    # CrossHair ConditionCheckable has ctxfn.name
    ctxfn = getattr(inner, "ctxfn", None)
    if ctxfn is not None:
        name = getattr(ctxfn, "name", None)
        if isinstance(name, str):
            return name

    # Try other common attributes on the unwrapped checkable
    # Loop invariant: checked attributes[0..i]
    for attr in ("fn", "function", "name"):
        obj = getattr(inner, attr, None)
        if obj is None:
            continue
        candidate = getattr(obj, "__name__", None)
        if not isinstance(candidate, str):
            candidate = getattr(obj, "name", None)
        if isinstance(candidate, str):
            return candidate

    # Last resort: try to extract a name from the string representation
    checkable_str = str(checkable)
    if "ctxfn=Function" in checkable_str:
        # Pattern: ClampedCheckable(ConditionCheckable(ctxfn=Function(name='foo'...
        import re as _re
        name_match = _re.search(r"name='([^']+)'", checkable_str)
        if name_match:
            return name_match.group(1)

    return checkable_str[:80]


@icontract.require(lambda checkable: checkable is not None, "checkable must be provided")
@icontract.ensure(lambda result: result is not None, "result must be the unwrapped checkable")
def _unwrap_checkable(checkable: Any) -> Any:
    """Walk wrapper layers (`_checkable`, `inner`, `_inner`) up to 5 deep."""
    inner = checkable
    # Loop invariant: inner is the most deeply unwrapped checkable found so far
    for _depth in range(5):
        wrapped: Any = None
        # Loop invariant: wrapped is the first attribute found in attrs[0..i]
        for attr in _CHECKABLE_WRAPPER_ATTRS:
            candidate = getattr(inner, attr, None)
            if candidate is not None:
                wrapped = candidate
                break
        if wrapped is None:
            return inner
        inner = wrapped
    return inner


@icontract.require(
    lambda func_name: is_non_empty_string(func_name),
    "func_name must be a non-empty string",
)
@icontract.require(
    lambda module_path: is_non_empty_string(module_path),
    "module_path must be a non-empty string",
)
@icontract.require(
    lambda elapsed: elapsed >= 0.0,
    "elapsed must be non-negative",
)
@icontract.ensure(
    lambda result: isinstance(result, SymbolicFinding),
    "result must be a SymbolicFinding",
)
def _message_to_finding(
    func_name: str,
    module_path: str,
    msg: Any,
    elapsed: float,
) -> SymbolicFinding:
    """Convert a CrossHair AnalysisMessage to a SymbolicFinding.

    Args:
        func_name: Function name.
        module_path: Module path.
        msg: CrossHair analysis message.
        elapsed: Time taken.

    Returns:
        A SymbolicFinding.
    """
    message_str = getattr(msg, "message", str(msg))
    state = getattr(msg, "state", None)
    state_name = str(getattr(state, "name", "")) if state else ""

    if state_name == "CONFIRMED":
        # CONFIRMED means postconditions hold for all paths — success
        return SymbolicFinding(
            function_name=func_name,
            module_path=module_path,
            outcome="verified",
            message=f"Verified: postconditions hold for '{func_name}'",
            duration_seconds=elapsed,
        )
    elif state_name == "POST_FAIL":
        return SymbolicFinding(
            function_name=func_name,
            module_path=module_path,
            outcome="counterexample",
            message=f"Postcondition violated for '{func_name}': {message_str}",
            counterexample=_parse_counterexample(str(message_str)),
            duration_seconds=elapsed,
        )
    elif state_name == "CANNOT_CONFIRM":
        return SymbolicFinding(
            function_name=func_name,
            module_path=module_path,
            outcome="timeout",
            message=f"Cannot confirm postcondition for '{func_name}': {message_str}",
            duration_seconds=elapsed,
        )
    elif state_name in ("EXEC_ERR", "SYNTAX_ERR", "IMPORT_ERR"):
        # Check if this is a solver limitation rather than a real bug
        msg_lower = str(message_str).lower()
        is_solver_issue = any(p in msg_lower for p in _SOLVER_LIMITATION_PATTERNS)
        is_solver_issue = is_solver_issue or "recursionerror" in msg_lower
        outcome = "unsupported" if is_solver_issue else "error"
        return SymbolicFinding(
            function_name=func_name,
            module_path=module_path,
            outcome=outcome,
            message=f"Error verifying '{func_name}': {message_str}",
            duration_seconds=elapsed,
        )
    elif state_name == "PRE_UNSAT":
        return SymbolicFinding(
            function_name=func_name,
            module_path=module_path,
            outcome="verified",
            message=f"Preconditions unsatisfiable for '{func_name}' — vacuously true",
            duration_seconds=elapsed,
        )
    else:
        # Check if the message indicates a solver limitation
        msg_lower = str(message_str).lower()
        is_solver_issue = any(p in msg_lower for p in _SOLVER_LIMITATION_PATTERNS)
        is_solver_issue = is_solver_issue or "recursionerror" in msg_lower
        if is_solver_issue:
            return SymbolicFinding(
                function_name=func_name,
                module_path=module_path,
                outcome="unsupported",
                message=f"Solver limitation for '{func_name}': {message_str}",
                duration_seconds=elapsed,
            )
        return SymbolicFinding(
            function_name=func_name,
            module_path=module_path,
            outcome="counterexample",
            message=f"Issue found for '{func_name}': {message_str}",
            counterexample=_parse_counterexample(str(message_str)),
            duration_seconds=elapsed,
        )


@icontract.require(lambda message: isinstance(message, str), "message must be a string")
@icontract.ensure(
    lambda result: result is None or isinstance(result, dict),
    "result must be a dictionary or None",
)
def _parse_counterexample(message: str) -> dict[str, object] | None:
    """Extract counterexample values from a CrossHair message.

    Args:
        message: The error message to parse.

    Returns:
        Dict of variable->value mappings, or None.
    """
    call_match = re.search(r"when calling \w+\((.+?)\)", message)
    if call_match:
        args_str = call_match.group(1)
        counterexample: dict[str, object] = {}
        # Loop invariant: counterexample contains parsed args from parts[0..i]
        for part in args_str.split(","):
            part = part.strip()
            if "=" in part:
                key, val = part.split("=", 1)
                counterexample[key.strip()] = val.strip()
        return counterexample if counterexample else None
    return None


@icontract.require(
    lambda module_path: is_non_empty_string(module_path),
    "module_path must be a non-empty string",
)
@icontract.require(lambda stdout: isinstance(stdout, str), "stdout must be a string")
@icontract.require(lambda stderr: isinstance(stderr, str), "stderr must be a string")
@icontract.ensure(lambda result: isinstance(result, list), "result must be a list")
def _parse_cli_output(
    module_path: str,
    stdout: str,
    stderr: str,
    function_name: str = "<unknown>",
) -> list[SymbolicFinding]:
    """Parse CrossHair CLI output into findings.

    Args:
        module_path: Module that was verified.
        stdout: CLI stdout.
        stderr: CLI stderr.

    Returns:
        List of findings parsed from CLI output.
    """
    findings: list[SymbolicFinding] = []

    if not stdout.strip() and not stderr.strip():
        return [SymbolicFinding(
            function_name=function_name,
            module_path=module_path,
            outcome="verified",
            message=(
                f"Function '{function_name}' verified successfully"
                if function_name != "<unknown>"
                else f"All functions in '{module_path}' verified successfully"
            ),
        )]

    line_pattern = re.compile(r"^(.+?):(\d+):\s*error:\s*(.+)$")

    # Loop invariant: findings contains parsed results for lines[0..i]
    for line in stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        match = line_pattern.match(line)
        if match:
            findings.append(SymbolicFinding(
                function_name=function_name,
                module_path=module_path,
                outcome="counterexample",
                message=match.group(3),
                counterexample=_parse_counterexample(match.group(3)),
            ))
        elif "error" in line.lower():
            findings.append(SymbolicFinding(
                function_name=function_name,
                module_path=module_path,
                outcome="error",
                message=line,
            ))

    if not findings and stderr.strip():
        findings.append(SymbolicFinding(
            function_name=function_name,
            module_path=module_path,
            outcome="error",
            message=f"CrossHair error: {stderr[:200]}",
        ))

    return findings


@icontract.require(
    lambda module_path: is_non_empty_string(module_path),
    "module_path must be a non-empty string",
)
@icontract.require(
    lambda module_timeout: is_positive_int(module_timeout),
    "module_timeout must be positive",
)
@icontract.ensure(
    lambda result: isinstance(result, SymbolicFinding),
    "result must be a SymbolicFinding",
)
def _make_module_timeout_finding(
    module_path: str,
    module_timeout: int,
) -> SymbolicFinding:
    """Create a module-level timeout finding for CLI-backed verification."""
    return SymbolicFinding(
        function_name="<module>",
        module_path=module_path,
        outcome="timeout",
        message=f"Module verification timed out after {module_timeout}s",
        duration_seconds=float(module_timeout),
    )


@icontract.require(
    lambda search_paths: isinstance(search_paths, tuple),
    "search_paths must be a tuple",
)
@icontract.ensure(lambda result: isinstance(result, dict), "result must be a dictionary")
def _subprocess_env(search_paths: tuple[str, ...]) -> dict[str, str]:
    """Build subprocess environment with project import roots on PYTHONPATH."""
    from serenecode.adapters import safe_subprocess_env

    extra: dict[str, str] = {}
    paths: list[str] = list(search_paths)
    existing = os.environ.get("PYTHONPATH", "")

    if existing:
        paths.append(existing)

    if paths:
        extra["PYTHONPATH"] = os.pathsep.join(paths)

    return safe_subprocess_env(extra_paths=extra)
