"""L3 coverage-gap tests for adapter subprocess/coverage/crosshair helpers.

Targets specific uncovered lines and branches flagged by Level 3
verification:

- serenecode.adapters.safe_subprocess_env — SERENECODE_DEBUG branch
- serenecode.adapters.coverage_adapter._check_coverage_error — error branch
- serenecode.adapters.coverage_adapter._build_coverage_findings — failure
  message and suggestion-generation branches
- serenecode.adapters.coverage_adapter._find_file_coverage_data — resolved
  path match and OSError/ValueError continue branches
- serenecode.adapters.crosshair_adapter._filter_autogenerated — both loop
  branches (dunder filtered vs. kept)
- serenecode.adapters.crosshair_adapter._verify_checkables — verified,
  message, and exception branches

Uses duck-typed fakes for CrossHair-internal types (same convention as
tests/integration/test_crosshair_adapter_helpers.py) so no CrossHair
import is required.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest

from serenecode.adapters import safe_subprocess_env
from serenecode.adapters.coverage_adapter import (
    _FunctionCoverage,
    _FunctionNode,
    _build_coverage_findings,
    _check_coverage_error,
    _find_file_coverage_data,
)
from serenecode.adapters.crosshair_adapter import (
    _filter_autogenerated,
    _verify_checkables,
)
from serenecode.ports.symbolic_checker import SymbolicFinding


# ---------------------------------------------------------------------------
# safe_subprocess_env — debug print branch (lines 74-76)
# ---------------------------------------------------------------------------


class TestSafeSubprocessEnvDebug:
    def test_debug_env_var_prints_keys_to_stderr(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Lines 74-76: SERENECODE_DEBUG set → key listing printed to stderr."""
        monkeypatch.setenv("SERENECODE_DEBUG", "1")
        env = safe_subprocess_env()
        captured = capsys.readouterr()
        assert isinstance(env, dict)
        assert "[serenecode] subprocess environment keys" in captured.err
        # All env keys should be named in the debug output
        for key in env:
            assert key in captured.err

    def test_no_debug_env_var_prints_nothing(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Opposite branch: SERENECODE_DEBUG unset → silent."""
        monkeypatch.delenv("SERENECODE_DEBUG", raising=False)
        env = safe_subprocess_env(extra_paths={"PYTHONPATH": "/some/src"})
        captured = capsys.readouterr()
        assert captured.err == ""
        assert env["PYTHONPATH"] == "/some/src"

    def test_debug_with_extra_paths_includes_extra_key(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Debug branch with extra_paths: merged key appears in the listing."""
        monkeypatch.setenv("SERENECODE_DEBUG", "yes")
        env = safe_subprocess_env(extra_paths={"MYPYPATH": "/stubs"})
        captured = capsys.readouterr()
        assert env["MYPYPATH"] == "/stubs"
        assert "MYPYPATH" in captured.err


# ---------------------------------------------------------------------------
# _check_coverage_error — error branch (line 263)
# ---------------------------------------------------------------------------


class TestCheckCoverageError:
    def test_string_error_returns_failure_finding(self) -> None:
        """Line 263: '_error' string present → CoverageFinding returned."""
        finding = _check_coverage_error({"_error": "pytest crashed"}, "mod.py")
        assert finding is not None
        assert finding.function_name == "<module>"
        assert finding.module_path == "mod.py"
        assert finding.meets_threshold is False
        assert "pytest crashed" in finding.message
        assert finding.line_coverage_percent == 0.0
        assert finding.branch_coverage_percent == 0.0

    def test_no_error_key_returns_none(self) -> None:
        """Opposite branch: no '_error' key → None."""
        result = _check_coverage_error({"files": {}}, "mod.py")
        assert result is None

    def test_non_string_error_returns_none(self) -> None:
        """Opposite branch: '_error' present but not a string → None."""
        result = _check_coverage_error({"_error": 42}, "mod.py")
        assert result is None


# ---------------------------------------------------------------------------
# _build_coverage_findings — failure branches (lines 353, 361)
# ---------------------------------------------------------------------------


_SOURCE = """\
def target(x):
    if x > 0:
        return 1
    return 0
"""


def _make_node(line_start: int = 1, line_end: int = 4) -> _FunctionNode:
    return _FunctionNode(
        name="target",
        qualified_name="target",
        line_start=line_start,
        line_end=line_end,
        is_method=False,
        class_name=None,
    )


class TestBuildCoverageFindings:
    def test_below_threshold_with_missing_lines_generates_suggestions(self) -> None:
        """Lines 353 and 361: not meets + missing lines → suggestions + fail msg."""
        fc = _FunctionCoverage(
            function=_make_node(),
            total_lines=4,
            executed_lines=frozenset({1, 2}),
            missing_lines=frozenset({3, 4}),
            total_branches=2,
            executed_branches=((2, 3),),
            missing_branches=((2, 4),),
        )
        findings = _build_coverage_findings([fc], _SOURCE, "mod.py", 80.0)
        assert len(findings) == 1
        finding = findings[0]
        assert finding.meets_threshold is False
        assert "2 lines uncovered" in finding.message
        assert finding.line_coverage_percent == 50.0
        assert finding.uncovered_lines == (3, 4)
        # Suggestions were generated for the uncovered block
        assert len(finding.suggestions) > 0

    def test_below_threshold_without_missing_lines_has_no_suggestions(self) -> None:
        """Branch 352->355 (false side): branch-only failure → no suggestions."""
        fc = _FunctionCoverage(
            function=_make_node(),
            total_lines=4,
            executed_lines=frozenset({1, 2, 3, 4}),
            missing_lines=frozenset(),
            total_branches=2,
            executed_branches=(),
            missing_branches=((2, 3), (2, 4)),
        )
        findings = _build_coverage_findings([fc], _SOURCE, "mod.py", 80.0)
        assert len(findings) == 1
        finding = findings[0]
        assert finding.meets_threshold is False
        assert finding.suggestions == ()
        assert "0 lines uncovered" in finding.message
        assert finding.branch_coverage_percent == 0.0

    def test_meets_threshold_uses_success_message(self) -> None:
        """Opposite branch (line 355-359): meets → success-style message."""
        fc = _FunctionCoverage(
            function=_make_node(),
            total_lines=4,
            executed_lines=frozenset({1, 2, 3, 4}),
            missing_lines=frozenset(),
            total_branches=0,
            executed_branches=(),
            missing_branches=(),
        )
        findings = _build_coverage_findings([fc], _SOURCE, "mod.py", 80.0)
        assert len(findings) == 1
        finding = findings[0]
        assert finding.meets_threshold is True
        assert "uncovered" not in finding.message
        assert finding.line_coverage_percent == 100.0
        assert finding.branch_coverage_percent == 100.0

    def test_empty_input_returns_empty_list(self) -> None:
        """Loop-exit branch with zero iterations."""
        findings = _build_coverage_findings([], _SOURCE, "mod.py", 80.0)
        assert findings == []


# ---------------------------------------------------------------------------
# _find_file_coverage_data — resolved-path branches (lines 761-763)
# ---------------------------------------------------------------------------


class TestFindFileCoverageData:
    def test_matches_by_resolved_path_when_files_do_not_exist(
        self, tmp_path: Path
    ) -> None:
        """Line 761: neither path exists on disk → match by resolved string."""
        missing = tmp_path / "does_not_exist.py"
        # Same file addressed through a redundant ./ segment resolves equal
        key = str(tmp_path / "." / "does_not_exist.py")
        coverage_data = {"files": {key: {"executed_lines": [1, 2]}}}
        result = _find_file_coverage_data(coverage_data, str(missing))
        assert result == {"executed_lines": [1, 2]}

    def test_resolved_paths_differ_returns_none(self, tmp_path: Path) -> None:
        """Branch 760->752 (false side): resolved strings differ → None."""
        coverage_data = {"files": {str(tmp_path / "a.py"): {"executed_lines": [1]}}}
        result = _find_file_coverage_data(coverage_data, str(tmp_path / "b.py"))
        assert result is None

    def test_value_error_during_resolution_is_skipped(self, tmp_path: Path) -> None:
        """Lines 762-763: embedded null byte → ValueError → continue."""
        bad_key = "bad\x00key.py"
        good_key = str(tmp_path / "." / "found.py")
        coverage_data = {
            "files": {
                bad_key: {"executed_lines": [9]},
                good_key: {"executed_lines": [1]},
            }
        }
        result = _find_file_coverage_data(coverage_data, str(tmp_path / "found.py"))
        assert result == {"executed_lines": [1]}

    def test_samefile_branch_when_both_exist(self, tmp_path: Path) -> None:
        """Existing-file branch (lines 754-756) still returns the entry."""
        f = tmp_path / "real.py"
        f.write_text("x = 1\n", encoding="utf-8")
        coverage_data = {"files": {str(f): {"executed_lines": [1]}}}
        result = _find_file_coverage_data(coverage_data, str(f))
        assert result == {"executed_lines": [1]}

    def test_both_exist_but_different_files_returns_none(self, tmp_path: Path) -> None:
        """Branch 755->752: both paths exist, samefile False → keep looking."""
        a = tmp_path / "a.py"
        b = tmp_path / "b.py"
        a.write_text("x = 1\n", encoding="utf-8")
        b.write_text("y = 2\n", encoding="utf-8")
        coverage_data = {"files": {str(a): {"executed_lines": [1]}}}
        result = _find_file_coverage_data(coverage_data, str(b))
        assert result is None

    def test_empty_files_dict_returns_none(self) -> None:
        """Zero-iteration loop branch → falls through to None."""
        result = _find_file_coverage_data({"files": {}}, "/tmp/whatever.py")
        assert result is None


# ---------------------------------------------------------------------------
# Fakes for CrossHair checkables (duck-typed, no crosshair import)
# ---------------------------------------------------------------------------


@dataclass
class _FakeCtxFn:
    name: str = "fake_func"


class _FakeCheckable:
    """Mimics CrossHair's ConditionCheckable shape."""

    def __init__(
        self,
        name: str = "fake_func",
        messages: list[Any] | None = None,
        raises: Exception | None = None,
    ) -> None:
        self.ctxfn = _FakeCtxFn(name=name)
        self._messages = messages if messages is not None else []
        self._raises = raises

    def analyze(self) -> list[Any]:
        if self._raises is not None:
            raise self._raises
        return list(self._messages)


@dataclass
class _FakeState:
    name: str


@dataclass
class _FakeMsg:
    message: str = ""
    state: object = None


@dataclass
class _DunderHostDataclass:
    """Module-level dataclass so _is_autogenerated_dunder can find it."""

    x: int = 0


def _make_dunder_checkable() -> _FakeCheckable:
    """Build a checkable that looks like _DunderHostDataclass.__hash__."""
    # Note: the class itself (not an instance) — __qualname__ passed to
    # type() becomes the class's qualname and is not visible on instances.
    fn = type(
        "_Fn",
        (),
        {
            "__qualname__": "_DunderHostDataclass.__hash__",
            "__module__": _DunderHostDataclass.__module__,
            "__name__": "__hash__",
        },
    )
    checkable = _FakeCheckable(name="__hash__")
    checkable.ctxfn.fn = fn  # type: ignore[attr-defined]
    return checkable


# ---------------------------------------------------------------------------
# _filter_autogenerated (lines 650, 652-655, 662-663)
# ---------------------------------------------------------------------------


class TestFilterAutogenerated:
    def test_dunder_is_filtered_and_recorded_verified(self) -> None:
        """Lines 652-655 (true branch): dataclass dunder → finding, not kept."""
        # The dataclass class must be resolvable in its module's namespace
        assert (
            getattr(
                sys.modules[_DunderHostDataclass.__module__],
                "_DunderHostDataclass",
                None,
            )
            is _DunderHostDataclass
        )
        dunder = _make_dunder_checkable()
        findings: list[SymbolicFinding] = []
        result = _filter_autogenerated([dunder], findings, "mod.py")
        assert result == []
        assert len(findings) == 1
        assert findings[0].function_name == "__hash__"
        assert findings[0].outcome == "verified"
        assert "correct by construction" in findings[0].message
        assert findings[0].module_path == "mod.py"

    def test_regular_checkable_is_kept(self) -> None:
        """Lines 662-663 (else branch): non-dunder → kept, no finding."""
        regular = _FakeCheckable(name="ordinary_function")
        findings: list[SymbolicFinding] = []
        result = _filter_autogenerated([regular], findings, "mod.py")
        assert result == [regular]
        assert findings == []

    def test_mixed_list_splits_correctly(self) -> None:
        """Both loop branches in a single pass."""
        dunder = _make_dunder_checkable()
        regular = _FakeCheckable(name="ordinary_function")
        findings: list[SymbolicFinding] = []
        result = _filter_autogenerated([dunder, regular], findings, "mod.py")
        assert result == [regular]
        assert len(findings) == 1
        assert findings[0].function_name == "__hash__"

    def test_empty_list_returns_empty(self) -> None:
        """Zero-iteration loop branch (line 650 and loop exit)."""
        findings: list[SymbolicFinding] = []
        result = _filter_autogenerated([], findings, "mod.py")
        assert result == []
        assert findings == []


# ---------------------------------------------------------------------------
# _verify_checkables (lines 689-696, 703-704, 707-710)
# ---------------------------------------------------------------------------


class TestVerifyCheckables:
    def test_no_messages_yields_verified_finding(self) -> None:
        """Lines 689-696: analyze() returns [] → verified finding."""
        checkable = _FakeCheckable(name="clean_func", messages=[])
        findings: list[SymbolicFinding] = []
        _verify_checkables([checkable], findings, "mod.py")
        assert len(findings) == 1
        assert findings[0].function_name == "clean_func"
        assert findings[0].outcome == "verified"
        assert "clean_func" in findings[0].message
        assert findings[0].duration_seconds >= 0.0

    def test_messages_are_converted_to_findings(self) -> None:
        """Lines 703-704: analyze() returns messages → one finding per message."""
        msgs = [
            _FakeMsg(message="ok", state=_FakeState("CONFIRMED")),
            _FakeMsg(
                message="postcondition violated when calling f(x = -1)",
                state=_FakeState("POST_FAIL"),
            ),
        ]
        checkable = _FakeCheckable(name="flaky_func", messages=msgs)
        findings: list[SymbolicFinding] = []
        _verify_checkables([checkable], findings, "mod.py")
        assert len(findings) == 2
        assert findings[0].outcome == "verified"
        assert findings[1].outcome == "counterexample"
        assert all(f.function_name == "flaky_func" for f in findings)

    def test_analyze_exception_is_classified_error(self) -> None:
        """Lines 707-710: analyze() raises plain error → 'error' finding."""
        checkable = _FakeCheckable(name="broken_func", raises=ValueError("boom"))
        findings: list[SymbolicFinding] = []
        _verify_checkables([checkable], findings, "mod.py")
        assert len(findings) == 1
        assert findings[0].function_name == "broken_func"
        assert findings[0].outcome == "error"
        assert "boom" in findings[0].message

    def test_analyze_exception_solver_limitation_is_unsupported(self) -> None:
        """Exception path with solver-limitation text → 'unsupported'."""
        checkable = _FakeCheckable(
            name="deep_func", raises=RuntimeError("unsupported operation")
        )
        findings: list[SymbolicFinding] = []
        _verify_checkables([checkable], findings, "mod.py")
        assert len(findings) == 1
        assert findings[0].outcome == "unsupported"

    def test_multiple_checkables_all_processed(self) -> None:
        """Loop covers success and failure iterations in one call."""
        ok = _FakeCheckable(name="ok_func", messages=[])
        bad = _FakeCheckable(name="bad_func", raises=ValueError("nope"))
        findings: list[SymbolicFinding] = []
        _verify_checkables([ok, bad], findings, "mod.py")
        assert len(findings) == 2
        assert {f.function_name for f in findings} == {"ok_func", "bad_func"}

    def test_empty_checkables_appends_nothing(self) -> None:
        """Zero-iteration loop branch."""
        findings: list[SymbolicFinding] = []
        result = _verify_checkables([], findings, "mod.py")
        assert result is None
        assert findings == []
