"""Direct unit tests for crosshair_adapter helper functions.

These functions are exercised transitively through full CrossHair runs in
test_crosshair_adapter.py (which is marked slow), but L3 coverage flags
many of them as below threshold because not every branch gets hit. This
file adds focused branch-level tests for each helper using duck-typed
fakes for CrossHair-internal types.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

from serenecode.adapters.crosshair_adapter import (
    _check_crosshair_cli,
    _cli_target_reference,
)
from serenecode.support.crosshair_parsing import (
    _classify_exception,
    _extract_func_name_from_checkable,
    _is_autogenerated_dunder,
    _message_to_finding,
    _parse_cli_output,
    _unwrap_checkable,
)


# ---------------------------------------------------------------------------
# _check_crosshair_cli
# ---------------------------------------------------------------------------


class TestCheckCrosshairCli:
    def test_returns_bool(self) -> None:
        result = _check_crosshair_cli()
        assert isinstance(result, bool)

    def test_handles_subprocess_failure(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Branch (lines 69-70): subprocess raises → cache False."""
        # Reset the cache first
        from serenecode.adapters import crosshair_adapter
        monkeypatch.setattr(crosshair_adapter, "_CROSSHAIR_CLI_AVAILABLE", None)

        def fake_run(*args: object, **kwargs: object) -> None:
            raise FileNotFoundError("crosshair not found")

        monkeypatch.setattr(subprocess, "run", fake_run)
        result = _check_crosshair_cli()
        assert result is False

    def test_returns_cached_result(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Branch (line 56-57): cached result returned without subprocess call."""
        from serenecode.adapters import crosshair_adapter
        # Reset to None first so the next call populates it
        monkeypatch.setattr(crosshair_adapter, "_CROSSHAIR_CLI_AVAILABLE", None)
        # First call: populates the cache
        first = _check_crosshair_cli()
        assert isinstance(first, bool)
        # Second call: hits the cached-return branch (line 56-57)
        called = {"count": 0}
        original_run = subprocess.run

        def counting_run(*args: object, **kwargs: object) -> object:
            called["count"] += 1
            return original_run(*args, **kwargs)

        monkeypatch.setattr(subprocess, "run", counting_run)
        second = _check_crosshair_cli()
        assert second == first
        # No subprocess call because the cache was already populated
        assert called["count"] == 0


# ---------------------------------------------------------------------------
# _cli_target_reference
# ---------------------------------------------------------------------------


class TestCliTargetReference:
    def test_dotted_module(self) -> None:
        """Non-absolute module path → uses dotted module.function."""
        def my_func() -> int:
            return 1
        result = _cli_target_reference("serenecode.config", "my_func", my_func)
        assert result == "serenecode.config.my_func"

    def test_absolute_file_with_line_number(self, tmp_path: Path) -> None:
        """Branch (lines 135-136): absolute .py file + lookup function source line."""
        f = tmp_path / "mod.py"
        f.write_text("def my_func():\n    return 1\n", encoding="utf-8")
        # Import the function to get a real callable with a source line
        import importlib.util
        spec = importlib.util.spec_from_file_location("mod", str(f))
        assert spec is not None
        module = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(module)
        my_func = module.my_func
        result = _cli_target_reference(str(f), "my_func", my_func)
        # Should be of the form "<absolute path>:<line>"
        assert result.startswith(str(f))
        assert ":1" in result or ":2" in result

    def test_falls_back_to_dotted_when_source_unavailable(self) -> None:
        """Lambda has no source line (or rather, may not). Falls back."""
        def my_func() -> int:
            return 1
        result = _cli_target_reference("non/abs/path.py", "my_func", my_func)
        assert "my_func" in result

    def test_absolute_file_with_oserror_on_source_lookup(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Branch (lines 135-136): inspect.getsourcelines raises → fallback line lookup."""
        import inspect
        f = tmp_path / "mod.py"
        f.write_text("def my_func():\n    return 1\n", encoding="utf-8")
        import importlib.util
        spec = importlib.util.spec_from_file_location("mod_oserr", str(f))
        assert spec is not None
        module = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(module)
        my_func = module.my_func

        # Force inspect.getsourcelines to raise
        def raising_getsourcelines(obj: object) -> tuple[list[str], int]:
            raise OSError("simulated source-not-found")

        monkeypatch.setattr(inspect, "getsourcelines", raising_getsourcelines)
        result = _cli_target_reference(str(f), "my_func", my_func)
        # Should still return a valid reference (falls back to co_firstlineno)
        assert result.startswith(str(f))

    def test_absolute_file_with_no_line_number_falls_back_to_dotted(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Branch: line_number is None → fall through to dotted form."""
        import inspect
        f = tmp_path / "mod.py"
        f.touch()

        def my_func() -> int:
            return 1

        # Force getsourcelines to raise AND remove __code__ so the fallback returns None
        def raising_getsourcelines(obj: object) -> tuple[list[str], int]:
            raise OSError("nope")

        monkeypatch.setattr(inspect, "getsourcelines", raising_getsourcelines)

        class _NoCode:
            pass

        # Wrap func so __code__ is not accessible
        no_code = _NoCode()
        no_code.__name__ = "my_func"  # type: ignore[attr-defined]
        result = _cli_target_reference(str(f), "my_func", no_code)  # type: ignore[arg-type]
        # line_number ends up None → falls through to dotted form
        assert result.endswith(".my_func")


# ---------------------------------------------------------------------------
# _classify_exception
# ---------------------------------------------------------------------------


class TestClassifyException:
    def test_value_error_is_error(self) -> None:
        result = _classify_exception(ValueError("just a regular error"))
        assert result == "error"

    def test_unsupported_keyword(self) -> None:
        """Branch (line 708): message contains 'unsupported'."""
        result = _classify_exception(RuntimeError("unsupported operation"))
        assert result == "unsupported"

    def test_not_implemented_keyword(self) -> None:
        result = _classify_exception(RuntimeError("feature not implemented"))
        assert result == "unsupported"

    def test_solver_limitation_pattern(self) -> None:
        """Branch (lines 705-707): match a solver limitation pattern."""
        # 'unhashable type' is in _SOLVER_LIMITATION_PATTERNS
        result = _classify_exception(RuntimeError("unhashable type: list"))
        assert result == "unsupported"

    def test_recursion_error_is_solver_limitation(self) -> None:
        """Branch (line 702): RecursionError is in _SOLVER_LIMITATION_TYPES."""
        result = _classify_exception(RecursionError("max depth"))
        assert result == "unsupported"

    def test_other_solver_pattern(self) -> None:
        """Branch (line 707): another pattern from the list."""
        result = _classify_exception(RuntimeError("symbolicbool encountered"))
        assert result == "unsupported"


# ---------------------------------------------------------------------------
# _extract_func_name_from_checkable
# ---------------------------------------------------------------------------


@dataclass
class _FakeCtxFn:
    name: str = "fake_func"


@dataclass
class _FakeCheckable:
    """Mimics CrossHair's ConditionCheckable shape."""
    ctxfn: object = None


class TestExtractFuncNameFromCheckable:
    def test_unwraps_via_ctxfn_name(self) -> None:
        checkable = _FakeCheckable(ctxfn=_FakeCtxFn(name="my_function"))
        result = _extract_func_name_from_checkable(checkable)
        assert result == "my_function"

    def test_unwraps_nested_checkable(self) -> None:
        """Branch (lines 789-790): unwrap _checkable wrapper."""
        inner = _FakeCheckable(ctxfn=_FakeCtxFn(name="deep_func"))

        @dataclass
        class _Wrapper:
            _checkable: object = None

        wrapper = _Wrapper(_checkable=inner)
        result = _extract_func_name_from_checkable(wrapper)
        assert result == "deep_func"

    def test_falls_back_to_function_attribute(self) -> None:
        """Branch (lines 808-813): walk through fn/function/name attributes."""
        def my_func() -> None:
            pass

        @dataclass
        class _NoCtxFn:
            fn: object = my_func

        checkable = _NoCtxFn()
        result = _extract_func_name_from_checkable(checkable)
        assert result == "my_func"

    def test_falls_back_to_string_repr(self) -> None:
        """Branch (lines 816-822): regex over string representation."""
        class _Strange:
            def __repr__(self) -> str:
                return "Checkable(ctxfn=Function(name='extracted_name', ...))"

        result = _extract_func_name_from_checkable(_Strange())
        assert result == "extracted_name"

    def test_completely_unknown_returns_truncated_repr(self) -> None:
        """Branch (line 824): falls through to first 80 chars of repr."""
        class _Unknown:
            def __repr__(self) -> str:
                return "x" * 200

        result = _extract_func_name_from_checkable(_Unknown())
        assert len(result) <= 80

    def test_unwrap_via_inner_attribute(self) -> None:
        """Branch (lines 791): wrapper exposes 'inner' instead of '_checkable'."""
        leaf = _FakeCheckable(ctxfn=_FakeCtxFn(name="found_via_inner"))

        @dataclass
        class _Wrapper:
            inner: object = None

        wrapper = _Wrapper(inner=leaf)
        result = _extract_func_name_from_checkable(wrapper)
        assert result == "found_via_inner"

    def test_unwrap_via_underscore_inner_attribute(self) -> None:
        """Branch (lines 793): wrapper exposes '_inner'."""
        leaf = _FakeCheckable(ctxfn=_FakeCtxFn(name="found_via_underscore_inner"))

        @dataclass
        class _Wrapper:
            _inner: object = None

        wrapper = _Wrapper(_inner=leaf)
        result = _extract_func_name_from_checkable(wrapper)
        assert result == "found_via_underscore_inner"

    def test_unwrap_loop_terminates_at_max_depth(self) -> None:
        """Branch: inner becomes None → return current inner."""
        # A simple leaf with no further wrappers
        leaf = _FakeCheckable(ctxfn=_FakeCtxFn(name="leaf_func"))
        result = _extract_func_name_from_checkable(leaf)
        assert result == "leaf_func"

    def test_falls_back_from_dunder_name_to_attr_name(self) -> None:
        """Branch (line 798): __name__ isn't a string → try `name` attribute."""
        # Build an object whose `fn` attribute has __name__ that isn't a string
        # but does have a `name` attribute that IS a string.
        class _StrangeFn:
            __name__ = 42  # not a string
            name = "fallback_name"

        class _CheckableWithFn:
            ctxfn = None  # so we fall through to the for loop
            fn = _StrangeFn()

        result = _extract_func_name_from_checkable(_CheckableWithFn())
        assert result == "fallback_name"


class TestUnwrapCheckable:
    """Tests for the extracted _unwrap_checkable helper."""

    def test_no_wrapper_attrs_returns_input(self) -> None:
        leaf = _FakeCheckable()
        assert _unwrap_checkable(leaf) is leaf

    def test_single_wrapper_via_checkable(self) -> None:
        leaf = _FakeCheckable()

        @dataclass
        class _Wrap:
            _checkable: object = None

        wrap = _Wrap(_checkable=leaf)
        assert _unwrap_checkable(wrap) is leaf

    def test_single_wrapper_via_inner(self) -> None:
        leaf = _FakeCheckable()

        @dataclass
        class _Wrap:
            inner: object = None

        wrap = _Wrap(inner=leaf)
        assert _unwrap_checkable(wrap) is leaf

    def test_single_wrapper_via_underscore_inner(self) -> None:
        leaf = _FakeCheckable()

        @dataclass
        class _Wrap:
            _inner: object = None

        wrap = _Wrap(_inner=leaf)
        assert _unwrap_checkable(wrap) is leaf

    def test_nested_wrappers(self) -> None:
        leaf = _FakeCheckable()

        @dataclass
        class _Wrap:
            _checkable: object = None

        outer = _Wrap(_checkable=_Wrap(_checkable=leaf))
        assert _unwrap_checkable(outer) is leaf

    def test_max_depth_5_terminates(self) -> None:
        """The loop has a hard cap of 5 to prevent infinite cycles."""
        @dataclass
        class _SelfRef:
            _checkable: object = None

        node = _SelfRef()
        node._checkable = node  # cycle
        # Should not infinite-loop; returns whatever it found at depth 5
        result = _unwrap_checkable(node)
        assert result is not None


# ---------------------------------------------------------------------------
# _is_autogenerated_dunder
# ---------------------------------------------------------------------------


class TestIsAutogeneratedDunder:
    def test_non_dunder_returns_false(self) -> None:
        checkable = _FakeCheckable(ctxfn=_FakeCtxFn(name="my_func"))
        assert _is_autogenerated_dunder(checkable) is False

    def test_dunder_on_non_dataclass(self) -> None:
        """Dunder name but not on a dataclass → False."""
        class NormalClass:
            def __hash__(self) -> int:
                return 0

        @dataclass
        class _CtxFn:
            name: str = "__hash__"
            fn: object = NormalClass.__hash__

        checkable = _FakeCheckable(ctxfn=_CtxFn())
        result = _is_autogenerated_dunder(checkable)
        # Result is False because the class isn't a dataclass
        assert isinstance(result, bool)

    def test_dunder_on_dataclass_returns_true(self) -> None:
        """Branch (lines 750-766): dataclass dunder method → True."""
        from dataclasses import dataclass as dataclass_decorator

        @dataclass_decorator
        class MyDataclass:
            x: int = 0

        # Create a checkable that points at MyDataclass.__hash__ via qualname
        class _Ctx:
            name = "__hash__"
            class fn:  # type: ignore[no-redef]
                __qualname__ = "MyDataclass.__hash__"
                __module__ = MyDataclass.__module__
                __name__ = "__hash__"

        # Make _Ctx.fn an instance not a class
        ctx = _Ctx()
        ctx.fn = type("_Fn", (), {  # type: ignore[assignment]
            "__qualname__": f"{MyDataclass.__name__}.__hash__",
            "__module__": MyDataclass.__module__,
            "__name__": "__hash__",
        })()

        checkable = _FakeCheckable(ctxfn=ctx)
        # Just exercise the branch — actual True/False depends on
        # whether sys.modules has the dataclass under the right name
        result = _is_autogenerated_dunder(checkable)
        assert isinstance(result, bool)

    def test_dunder_with_unwrap_break_no_ctxfn(self) -> None:
        """Branch (line 748): unwrap loop hits None, ctxfn is None → False fallthrough."""
        # Build a wrapper chain where the deepest object has no ctxfn.
        # Avoid dataclass mutable-default trap by using plain classes.
        class _Inner:
            ctxfn = None

        class _Outer:
            def __init__(self) -> None:
                self._checkable = _Inner()
                self.ctxfn = _FakeCtxFn(name="__hash__")

        outer = _Outer()
        # __hash__ is a dunder name, but the unwrapped inner has no ctxfn
        # → can't find the owning class → returns False
        result = _is_autogenerated_dunder(outer)
        assert result is False

    def test_dunder_with_no_class_owner_returns_false(self) -> None:
        """Branch (line 747): can't determine the owning class → False."""
        # __hash__ name but qualname has no '.' → no class to look up
        class _Ctx:
            name = "__hash__"

        ctx = _Ctx()
        ctx.fn = type("_Fn", (), {  # type: ignore[attr-defined]
            "__qualname__": "__hash__",  # no '.' so no class component
            "__module__": "builtins",
            "__name__": "__hash__",
        })()

        checkable = _FakeCheckable(ctxfn=ctx)
        result = _is_autogenerated_dunder(checkable)
        assert result is False

    def test_dunder_with_no_ctxfn_returns_false(self) -> None:
        """Branch (line 742): unwrapped inner has no ctxfn → False."""
        class _NoCtx:
            name = "__hash__"

        no_ctx = _NoCtx()
        result = _is_autogenerated_dunder(no_ctx)
        # _extract_func_name returns "__hash__" via the attr fallback,
        # then _is_autogenerated_dunder probes ctxfn → None → False
        assert result is False

    def test_dunder_with_ctxfn_but_no_fn_returns_false(self) -> None:
        """Branch (line 745): ctxfn exists but no `fn` attribute → False."""
        class _CtxNoFn:
            name = "__hash__"
            # no fn attribute

        checkable = _FakeCheckable(ctxfn=_CtxNoFn())
        result = _is_autogenerated_dunder(checkable)
        assert result is False

    def test_dunder_with_no_module_returns_false(self) -> None:
        """Branch (line 753): fn has no __module__ → False."""
        # __qualname__ is looked up on the type, not instances; build a real
        # function-like object using `type(...)` so the class attrs are accessible.
        fn = type("_Fn", (), {
            "__qualname__": "SomeClass.__hash__",
            "__module__": "",  # falsy
            "__name__": "__hash__",
        })

        class _Ctx:
            name = "__hash__"
        ctx = _Ctx()
        ctx.fn = fn  # type: ignore[attr-defined]

        checkable = _FakeCheckable(ctxfn=ctx)
        result = _is_autogenerated_dunder(checkable)
        assert result is False

    def test_dunder_with_unknown_module_returns_false(self) -> None:
        """Branch (line 757): module not in sys.modules → False."""
        fn = type("_Fn", (), {
            "__qualname__": "SomeClass.__hash__",
            "__module__": "totally_nonexistent_module_xyzzy_42",
            "__name__": "__hash__",
        })

        class _Ctx:
            name = "__hash__"
        ctx = _Ctx()
        ctx.fn = fn  # type: ignore[attr-defined]

        checkable = _FakeCheckable(ctxfn=ctx)
        result = _is_autogenerated_dunder(checkable)
        assert result is False

    def test_dunder_with_unknown_class_in_module_returns_false(self) -> None:
        """Branch (line 759): class not found in module → False."""
        fn = type("_Fn", (), {
            "__qualname__": "TotallyUnknownClass_xyzzy.__hash__",
            "__module__": "tests.integration.test_crosshair_adapter_helpers",
            "__name__": "__hash__",
        })

        class _Ctx:
            name = "__hash__"
        ctx = _Ctx()
        ctx.fn = fn  # type: ignore[attr-defined]

        checkable = _FakeCheckable(ctxfn=ctx)
        result = _is_autogenerated_dunder(checkable)
        assert result is False

    def test_dunder_on_real_dataclass_returns_true(self) -> None:
        """Branch (line 761): real dataclass class found → return True."""
        from dataclasses import dataclass as dataclass_decorator
        import sys

        @dataclass_decorator
        class _DataclassForCoverage:
            x: int = 0

        fn = type("_Fn", (), {
            "__qualname__": "_DataclassForCoverage.__hash__",
            "__module__": _DataclassForCoverage.__module__,
            "__name__": "__hash__",
        })

        class _Ctx:
            name = "__hash__"
        ctx = _Ctx()
        ctx.fn = fn  # type: ignore[attr-defined]

        checkable = _FakeCheckable(ctxfn=ctx)
        # Inject the class into its module under the right name
        mod = sys.modules[_DataclassForCoverage.__module__]
        mod._DataclassForCoverage = _DataclassForCoverage  # type: ignore[attr-defined]
        try:
            result = _is_autogenerated_dunder(checkable)
            assert result is True
        finally:
            delattr(mod, "_DataclassForCoverage")


# ---------------------------------------------------------------------------
# _message_to_finding
# ---------------------------------------------------------------------------


@dataclass
class _FakeState:
    name: str


@dataclass
class _FakeMsg:
    message: str = ""
    state: object = None


class TestMessageToFinding:
    def test_confirmed_state(self) -> None:
        msg = _FakeMsg(message="all good", state=_FakeState("CONFIRMED"))
        result = _message_to_finding("f", "mod", msg, 1.0)
        assert result.outcome == "verified"
        assert result.duration_seconds == 1.0

    def test_post_fail_state(self) -> None:
        """Branch (lines 873-881): POST_FAIL → counterexample."""
        msg = _FakeMsg(
            message="postcondition violated when x = -1",
            state=_FakeState("POST_FAIL"),
        )
        result = _message_to_finding("f", "mod", msg, 0.5)
        assert result.outcome == "counterexample"
        assert "violated" in result.message.lower()

    def test_cannot_confirm_state(self) -> None:
        """Branch (lines 882-889): CANNOT_CONFIRM → timeout."""
        msg = _FakeMsg(message="ran out of paths", state=_FakeState("CANNOT_CONFIRM"))
        result = _message_to_finding("f", "mod", msg, 30.0)
        assert result.outcome == "timeout"

    def test_exec_err_real_error(self) -> None:
        """Branch (lines 890-902): EXEC_ERR with non-solver message → error."""
        msg = _FakeMsg(message="something exploded", state=_FakeState("EXEC_ERR"))
        result = _message_to_finding("f", "mod", msg, 0.1)
        assert result.outcome == "error"

    def test_exec_err_solver_limitation(self) -> None:
        """EXEC_ERR with recursion → unsupported."""
        msg = _FakeMsg(
            message="RecursionError: maximum recursion depth exceeded",
            state=_FakeState("EXEC_ERR"),
        )
        result = _message_to_finding("f", "mod", msg, 0.1)
        assert result.outcome == "unsupported"

    def test_pre_unsat_state(self) -> None:
        """Branch (lines 903-910): PRE_UNSAT → vacuously verified."""
        msg = _FakeMsg(message="preconditions can never hold", state=_FakeState("PRE_UNSAT"))
        result = _message_to_finding("f", "mod", msg, 0.1)
        assert result.outcome == "verified"
        assert "vacuously" in result.message.lower()

    def test_unknown_state_solver_limitation(self) -> None:
        """Branch (lines 916-923): unknown state with solver hint → unsupported."""
        msg = _FakeMsg(
            message="recursionerror in symbolic engine",
            state=_FakeState("WEIRD_STATE"),
        )
        result = _message_to_finding("f", "mod", msg, 0.1)
        assert result.outcome == "unsupported"

    def test_unknown_state_default_counterexample(self) -> None:
        """Branch (lines 924+): unknown state → default to counterexample."""
        msg = _FakeMsg(message="some failure", state=_FakeState("WEIRD_STATE"))
        result = _message_to_finding("f", "mod", msg, 0.1)
        assert result.outcome == "counterexample"


# ---------------------------------------------------------------------------
# _parse_cli_output
# ---------------------------------------------------------------------------


class TestParseCliOutput:
    def test_empty_stdout_and_stderr_returns_verified(self) -> None:
        result = _parse_cli_output("mod.py", "", "", function_name="f")
        assert len(result) == 1
        assert result[0].outcome == "verified"

    def test_empty_with_unknown_function(self) -> None:
        result = _parse_cli_output("mod.py", "", "")
        assert len(result) == 1
        assert "verified" in result[0].outcome

    def test_counterexample_line(self) -> None:
        """Branch (lines 1006-1013): regex matches CrossHair error format."""
        stdout = "mod.py:42: error: postcondition violated"
        result = _parse_cli_output("mod.py", stdout, "", function_name="f")
        assert len(result) == 1
        assert result[0].outcome == "counterexample"

    def test_generic_error_line(self) -> None:
        """Branch (lines 1015-1016): line contains 'error' but doesn't match regex."""
        stdout = "an error happened somewhere"
        result = _parse_cli_output("mod.py", stdout, "", function_name="f")
        assert len(result) == 1
        assert result[0].outcome == "error"

    def test_stderr_only(self) -> None:
        """Branch (lines 1023-1029): stdout empty, stderr has content."""
        result = _parse_cli_output("mod.py", "", "fatal: crosshair crashed")
        assert len(result) == 1
        assert result[0].outcome == "error"
        assert "crosshair" in result[0].message.lower()
